---
- hosts: all
  gather_facts: yes
  become: yes
  remote_user: root
#variable
  vars:
    MYSQL_ROOT_PASSWORD: '123'
    MYSQL_DATABASE: thoitrang
    MYSQL_USER: quan
    MYSQL_PASSWORD: '123'
  tasks:

#copy file
    - name: create build directory
      file:
        path: "/root/{{item}}"
        state: directory
        owner: root
        group: root
        mode: '0755'
      with_items: ["file", "data"]
    
    - name: copy file
      copy:
        src: ./{{item}}
        dest: /root/file
        owner: root
        group: root
        mode: '0644'
      with_items: ["thoitrangdb.sql", "docker", "my.cnf", "conf"]

    # - name: Unarchive file & copy file 2
    #   unarchive:
    #     src: ./thoitrang.tar.gz
    #     dest: /root/file
#network
    # - name: Create docker networks
    #   docker_network:
    #     name: inet1
    #     driver: bridge

#app

    - name: Build Docker image from Dockerfile
      docker_image: 
        name: php-fpm-v
        path: /root/file/docker
        state: build

    - name: Running the container php-fpm
      docker_container:
        image: php-fpm-v:latest
        name: c-php
        detach: yes
        hostname: c-php
        state: started
        volumes: /root/file/thoitrang:/var/www/html
        ports: 9000:9000
        env:
          MYSQL_USER: "{{MYSQL_USER}}"
          MYSQL_PASSWORD: "{{MYSQL_PASSWORD}}"
    
    
    - name: nginx server in docker
      docker_container:
        name: c-nginx
        detach: yes
        image: nginx
        state: started
        hostname: c-nginx
        volumes: 
          - /root/file/thoitrang:/var/www/html
          - /root/file/conf:/etc/nginx/conf.d
        ports:
          - "80:80"
          - "443:443"

    - name: mysql server in docker
      docker_container:
        name: c-mysql
        detach: yes
        image: mysql
        state: started
        hostname: c-mysql
        volumes: 
          - /root/file/my.cnf:/etc/mysql/my.cnf
          - /root/file/:/docker-entrypoint-initdb.d
          - /root/data:/var/lib/mysql
          - /root/log:/var/log/mysql
        ports: 10.148.0.5:3306:3306
        env:
          MYSQL_ROOT_PASSWORD: "{{MYSQL_ROOT_PASSWORD}}"
          MYSQL_DATABASE: "{{MYSQL_DATABASE}}"
          MYSQL_USER: "{{MYSQL_USER}}"
          MYSQL_PASSWORD: "{{MYSQL_PASSWORD}}"
...     